/*
**  (C) 2007 by Remo Dentato (rdentato@users.sourceforge.net)
**
** Permission to use, copy, modify and distribute this code and
** its documentation for any purpose is hereby granted without
** fee, provided that the above copyright notice, or equivalent
** attribution acknowledgement, appears in all copies and
** supporting documentation.
**
** Copyright holder makes no representations about the suitability
** of this software for any purpose. It is provided "as is" without
** express or implied warranty.
*/

#include "yrx.h"

static FILE *outf;

static void dmp_plain_lbl(uint8_t *l)
{
  if (*l == 0) return;

  /*putchar(*l);*/
  l++;
  while (l[0] <= l[1]) {
    printf("%s",yrxLabelStr(*l++));
    printf("%s",yrxLabelStr(*l++));
  }
}

static void dmp_plain_tags(uint8_t *t)
{
  if (*t == 0) return;

  printf(" / ");

  while (t[0] != '\0') {
    printf("%s ",yrxTagStr(t[0],t[1]));
    t += 2;
  }
}


static void dmp_plain(aut *dfa)
{
  uint32_t from;
  Arc *a;

  from = yrxStartState(dfa);

  while (from != 0) {
    while ((a = yrxGetArc(dfa)) != NULL) {
      printf("%5d -> %-5d %p / %p  ", from, a->to, a->lbl, a->tags);
      dmp_plain_lbl(yrxArcLabel(a));
      dmp_plain_tags(yrxArcTags(a));
      printf("\n");
    }
    from = yrxNextState(dfa);
  }
}


static void dmp_dot(aut *dfa)
{
  uint32_t from;
  Arc *a;

  printf("// Generated by YRX \n\n");
  printf("digraph finite_state_machine {\n");
  printf("\trankdir=LR;\n");

  printf("\tnode [shape = circle];\n");
  
  from = yrxStartState(dfa);

  while (from != 0) {
    while ((a = yrxGetArc(dfa)) != NULL) {
      if (a->to == 0) {
        printf("\t%d [shape=box, style=rounded, peripheries=2, label=\"%d",from,from);
      }
      else {
        printf("\t %d -> %d [ label = \"", from, a->to);
        dmp_plain_lbl(yrxArcLabel(a));
      }
      dmp_plain_tags(yrxArcTags(a));
      printf("\" ] ;\n");
    }
    from = yrxNextState(dfa);
  }
  printf("}\n");
}


void yrxDump(aut *dfa, uint8_t fmt)
{

  switch (fmt) {
     case DMP_PLAIN: dmp_plain(dfa); break;
     case DMP_DOT:   dmp_dot(dfa); break;
  }

}
